export default function Head() {
  return (
    <>
      <title>Panaverse</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://www.panaverse.co/red-p-logo-text_dao_croped.png" />
    </>
  )
}
